---
BM_DIR: "{{ ROOT_DIR }}/block-manager"
BM_DATA_DIR: "{{ MNT_DATA }}/block-manager"
BM_LOGS_DIR: "{{ MNT_DATA }}/logs-block-manager"
AGQL_DIR: "{{ ROOT_DIR }}/archive-gql"
AGQL_LOGS_DIR: "{{ MNT_DATA }}/logs-archive-gql"
AGQL_DATA_DIR: "{{ MNT_DATA }}/archive-gql"
