# STREAM_SRC_URL
bk_stream_blocks_endpoint: https://node0:12000

# SQLITE_PATH
db_path: ./data

# BM_OWNER_WALLET_PUBKEY
bm_owner_wallet_pubkey: e2c9d4be54d342d3f0e6394a7738fc39b93d4fe3fdba317aa699f7305566de2b

# BM_ISSUER_KEYS_FILE
keys: config/block_manager_signing.keys.json

# DEFAULT_BP
default_bp: node0:8600

# TOKEN_TTL (in secs)
token_ttl: 30

contracts:
  bm_root:
    address: 0:6666666666666666666666666666666666666666666666666666666666666666
    abi: ../contracts/0.79.3_compiled/bksystem/BlockManagerContractRoot.abi.json

  license:
    abi: ../contracts/0.79.3_compiled/bksystem/LicenseBM.abi.json
