[alias]
lint = "clippy --workspace --tests --examples --bins -- -Dclippy::todo"
lint-all = "clippy --workspace --all-features --tests --examples --bins -- -Dclippy::todo"

[build]
rustflags = ["--cfg", "tokio_unstable"]

[net]
git-fetch-with-cli = true
