---
LOG_ROTATE_AMOUNT: 20
LOG_ROTATE_SIZE: 5G
LOG_ROTATE_SPEC: "*/2 *"

OPT_STATE_CLEANUP_SPEC: "0 *" # hourly
OPT_STATE_KEEP_AMOUNT: 100 # should not be less than 100

BLK_STATE_CLEANUP_SPEC: "0 *" # hourly
BLK_STATE_KEEP_AMOUNT: 100000 # less than 1000 may be dangerous, 100k should be safe and reasonable space wise

SHARE_CLEANUP_SPEC: "0 *" # hourly
SHARE_KEEP_AMOUNT: 3 # can be even 1, but better to use at least 2

NODE_BINARY: node
FAIL_FAST: yes
STAKING_TIME: 60

NUMACTL: no

OTEL_MY_HOST_NAME: "{{ inventory_hostname }}"

EXT_MESSAGE_AUTH_REQUIRED: no
AUTH_TOKEN: some-secret-auth-token

AEROSPIKE_IMAGE: "aerospike/aerospike-server:8.1.0.1"
LOGROTATE_IMAGE: "stakater/logrotate:3.13.0"

COMMIT_HASH: commit_unknown
TEST_NAME: test_unknown

MIN_TIME_BETWEEN_STATE_PUBLISH_DIRECTIVES: 1200s
NODE_JOINING_TIMEOUT: 600s

DISABLE_STAKING: no

NUMBERED_SERVICES: yes

NODE_CONFIGS:
  - zerostate

OTHER_KEYS: []

PREPARE_HOST: yes

WAIT_FOR_NODE_STOP_SECS: 600
NODE_STOP_TEST_OUTER_TAIL: 50000
# NODE_STOP_TEST_INNER_TAIL: 5
